#Requires -Version 5.1
<#
.SYNOPSIS
    Initialize machine state tracking files

.DESCRIPTION
    Creates the initial state tracking files required for Claude Agent operation:
    - worktrees.pool.md - Agent seat allocation tracking
    - worktrees.activity.md - Activity log
    - reflection.log.md - Learnings and patterns
    - pr-dependencies.md - Cross-repo PR tracking
    - instances.map.md - Instance ID mapping

.PARAMETER MachineContextPath
    Path to the machine context directory

.PARAMETER Force
    Overwrite existing files (default: skip if exists)
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [string]$MachineContextPath,

    [switch]$Force
)

$ErrorActionPreference = "Stop"

# Set default if not provided
if (-not $MachineContextPath) {
    $MachineContextPath = Join-Path (Split-Path $PSScriptRoot -Parent) "_machine"
}

function Write-Status {
    param([string]$Message, [string]$Type = "Info")
    $color = switch ($Type) {
        "Success" { "Green" }
        "Warning" { "Yellow" }
        "Error"   { "Red" }
        "Info"    { "Cyan" }
        default   { "White" }
    }
    $prefix = switch ($Type) {
        "Success" { "[OK]" }
        "Warning" { "[WARN]" }
        "Error"   { "[ERROR]" }
        "Info"    { "[INFO]" }
        default   { "[*]" }
    }
    Write-Host "$prefix $Message" -ForegroundColor $color
}

function Create-StateFile {
    param(
        [string]$Path,
        [string]$Content,
        [string]$Description
    )

    if ((Test-Path $Path) -and -not $Force) {
        Write-Status "$Description already exists (use -Force to overwrite)" "Warning"
        return $false
    }

    try {
        Set-Content -Path $Path -Value $Content -Encoding UTF8
        Write-Status "$Description created: $(Split-Path $Path -Leaf)" "Success"
        return $true
    } catch {
        Write-Status "Failed to create $Description : $_" "Error"
        return $false
    }
}

# === MAIN ===
Write-Host ""
Write-Host "Initializing Machine State Files" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan
Write-Host ""

# Ensure directory exists
if (-not (Test-Path $MachineContextPath)) {
    New-Item -ItemType Directory -Path $MachineContextPath -Force | Out-Null
    Write-Status "Created machine context directory" "Success"
}

$date = Get-Date -Format "yyyy-MM-dd HH:mm"

# === 1. WORKTREES POOL ===
$worktreesPoolContent = @"
# Worktree Pool Status

**Last Updated:** $date
**Purpose:** Track agent worktree allocations for parallel agent coordination

---

## Pool Status

| Agent | Status | Repo | Branch | Last Activity | Instance ID | Notes |
|-------|--------|------|--------|---------------|-------------|-------|
| agent-001 | FREE | - | - | - | - | Available |
| agent-002 | FREE | - | - | - | - | Available |
| agent-003 | FREE | - | - | - | - | Available |

---

## Status Definitions

- **FREE** - Available for allocation
- **BUSY** - Currently in use by an agent
- **STALE** - Busy > 2 hours with no activity (needs cleanup)
- **RESERVED** - Reserved for specific operation

---

## Allocation Protocol

1. Read this file BEFORE allocating
2. Find first FREE seat
3. Mark as BUSY with repo, branch, timestamp, instance ID
4. Work in worktree
5. After PR creation: Release worktree, mark FREE

---

**Auto-generated by bootstrap.ps1**
"@

Create-StateFile -Path (Join-Path $MachineContextPath "worktrees.pool.md") `
                 -Content $worktreesPoolContent `
                 -Description "Worktree pool status"

# === 2. WORKTREES ACTIVITY LOG ===
$activityLogContent = @"
# Worktree Activity Log

**Purpose:** Audit trail of all worktree allocations and releases

---

## Log Format

``````
timestamp | action | agent | repo | branch | instance | executor | notes
``````

### Actions
- ALLOCATE - Agent claimed a worktree seat
- RELEASE - Agent released a worktree seat
- CLEANUP - Stale worktree cleaned up
- PROVISION - New agent seat created

---

## Activity Log

$date | INIT | system | - | - | bootstrap | system | Bootstrap initialization

---

**Auto-generated by bootstrap.ps1**
"@

Create-StateFile -Path (Join-Path $MachineContextPath "worktrees.activity.md") `
                 -Content $activityLogContent `
                 -Description "Worktree activity log"

# === 3. REFLECTION LOG ===
$reflectionLogContent = @"
# Agent Reflection Log

**Purpose:** Document learnings, patterns, mistakes, and improvements discovered by Claude agents

---

## How to Use This File

After each session, agents should add entries documenting:
1. **Mistakes made** - What went wrong and why
2. **Lessons learned** - What was discovered
3. **Patterns identified** - Reusable approaches
4. **Improvements made** - Changes to documentation or tools

---

## Log Format

``````markdown
## YYYY-MM-DD HH:MM - Topic/Issue

**Context:** What was happening
**Issue:** What went wrong or what was discovered
**Resolution:** How it was fixed
**Lesson:** What to remember for future sessions
**Action:** Any documentation or tool updates made
``````

---

## Reflection Entries

### $date - Bootstrap Initialization

**Context:** Fresh environment setup
**Issue:** N/A - Initial setup
**Resolution:** N/A
**Lesson:** Remember to run bootstrap.ps1 after cloning to a new machine
**Action:** Bootstrap system created for automated environment setup

---

**Auto-generated by bootstrap.ps1**
"@

Create-StateFile -Path (Join-Path $MachineContextPath "reflection.log.md") `
                 -Content $reflectionLogContent `
                 -Description "Reflection log"

# === 4. PR DEPENDENCIES ===
$prDependenciesContent = @"
# Cross-Repository PR Dependencies

**Purpose:** Track PRs that depend on changes in other repositories

---

## How Dependencies Work

When a PR in repo A depends on a PR in repo B:
1. Create PR in repo B first (or simultaneously)
2. Add DEPENDENCY ALERT header to PR in repo A
3. Log the dependency here
4. Ensure merge order: B before A

---

## Active Dependencies

| Date | Dependent PR | Depends On | Status | Notes |
|------|--------------|------------|--------|-------|
| - | - | - | - | No active dependencies |

---

## Dependency Status

- **PENDING** - Both PRs open, waiting for review
- **PARTIAL** - Dependency merged, dependent still open
- **RESOLVED** - Both PRs merged in correct order
- **CONFLICT** - Merged out of order (needs fix)

---

## Completed Dependencies

| Date | Dependent PR | Depends On | Resolution |
|------|--------------|------------|------------|
| - | - | - | - |

---

**Auto-generated by bootstrap.ps1**
"@

Create-StateFile -Path (Join-Path $MachineContextPath "pr-dependencies.md") `
                 -Content $prDependenciesContent `
                 -Description "PR dependencies tracker"

# === 5. INSTANCES MAP ===
$instancesMapContent = @"
# Claude Instance Mapping

**Purpose:** Map Claude instance IDs to agent seats for multi-agent coordination

---

## How Instance Mapping Works

When multiple Claude agents run simultaneously:
1. Each agent has a unique instance ID (from CLAUDE_INSTANCE_ID or generated)
2. Instance ID maps to an agent seat (agent-001, agent-002, etc.)
3. Prevents conflicts when multiple agents allocate worktrees

---

## Active Mappings

| Instance ID | Agent Seat | Session Start | Last Activity | Status |
|-------------|------------|---------------|---------------|--------|
| - | - | - | - | No active instances |

---

## Instance Status

- **ACTIVE** - Instance is currently running
- **IDLE** - Instance running but no recent activity
- **CLOSED** - Instance terminated

---

**Auto-generated by bootstrap.ps1**
"@

Create-StateFile -Path (Join-Path $MachineContextPath "instances.map.md") `
                 -Content $instancesMapContent `
                 -Description "Instances map"

# === 6. KNOWLEDGE BASE SUMMARY (Optional) ===
$knowledgeBaseSummaryContent = @"
# Knowledge Base Summary

**Purpose:** Index of accumulated knowledge and patterns

---

## Categories

### API Development Patterns
- OpenAI config initialization patterns
- Response enrichment patterns
- URL handling patterns

### Git Workflow Patterns
- Worktree allocation protocol
- PR creation workflow
- Cross-repo dependencies

### CI/CD Patterns
- GitHub Actions troubleshooting
- Build error resolution
- Test failure diagnosis

### Code Quality Patterns
- C# auto-fix workflows
- Linting and formatting
- Review checklist

---

## Pattern Library Location

See: ``_machine/best-practices/`` for detailed pattern documentation

---

**Auto-generated by bootstrap.ps1**
"@

Create-StateFile -Path (Join-Path $MachineContextPath "KNOWLEDGE_BASE_SUMMARY.md") `
                 -Content $knowledgeBaseSummaryContent `
                 -Description "Knowledge base summary"

# === SUMMARY ===
Write-Host ""
Write-Host "==============================" -ForegroundColor Cyan
Write-Host "  Machine State Initialization" -ForegroundColor Cyan
Write-Host "==============================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Files created/verified in: $MachineContextPath" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  State files:" -ForegroundColor White
Write-Host "    - worktrees.pool.md      (agent allocation tracking)" -ForegroundColor DarkGray
Write-Host "    - worktrees.activity.md  (activity audit log)" -ForegroundColor DarkGray
Write-Host "    - reflection.log.md      (learnings and patterns)" -ForegroundColor DarkGray
Write-Host "    - pr-dependencies.md     (cross-repo PR tracking)" -ForegroundColor DarkGray
Write-Host "    - instances.map.md       (multi-agent coordination)" -ForegroundColor DarkGray
Write-Host "    - KNOWLEDGE_BASE_SUMMARY.md (pattern index)" -ForegroundColor DarkGray
Write-Host ""

Write-Status "Machine state initialization complete" "Success"
exit 0
