# Setup Social Media API Verification Tasks in ClickUp

$ErrorActionPreference = "Stop"

# ClickUp Config
$API_KEY = "pk_74525428_TXT8V1QUA13N7SCRM0UUM6WNQO2I2NML"
$API_BASE = "https://api.clickup.com/api/v2"
$LIST_ID = "901214097647" # Brand Designer list

$headers = @{
    "Authorization" = $API_KEY
    "Content-Type" = "application/json"
}

# Social media platforms to create tasks for
$platforms = @(
    @{
        name = "Facebook/Meta API Verification"
        file = "1_Facebook_Meta_API_Verification"
        description = "Complete Facebook/Meta Business Verification and App Review process for API access"
        timeline = "5-21 days"
        priority = "high"
    },
    @{
        name = "LinkedIn API Verification"
        file = "2_LinkedIn_API_Verification"
        description = "Complete LinkedIn Company Page Verification and API Products request"
        timeline = "3-8 weeks"
        priority = "high"
    },
    @{
        name = "TikTok API Verification"
        file = "3_TikTok_API_Verification"
        description = "Complete TikTok app registration, permissions request, and audit process"
        timeline = "4-8 weeks"
        priority = "medium"
    },
    @{
        name = "Instagram API Verification"
        file = "4_Instagram_API_Verification"
        description = "Setup Instagram Business Account and complete Meta App Review for Instagram permissions"
        timeline = "3-8 weeks"
        priority = "high"
    },
    @{
        name = "Medium API Integration (Deprecated)"
        file = "5_Medium_API_Verification"
        description = "Generate Medium integration token (Note: API deprecated, limited functionality)"
        timeline = "2 minutes"
        priority = "low"
    }
)

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Social Media API Tasks Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Search for existing tasks
Write-Host "Step 1: Searching for existing tasks..." -ForegroundColor Yellow

$searchTerms = @("Facebook API", "LinkedIn API", "TikTok API", "Instagram API", "Medium API", "social media API", "API verification")
$existingTasks = @{}

foreach ($term in $searchTerms) {
    try {
        $encodedTerm = [System.Web.HttpUtility]::UrlEncode($term)
        $response = Invoke-RestMethod -Uri "$API_BASE/list/$LIST_ID/task?subtasks=true" -Headers $headers -Method Get

        foreach ($task in $response.tasks) {
            $taskName = $task.name.ToLower()
            if ($taskName -match "facebook|meta|linkedin|tiktok|instagram|medium|social.*api") {
                $existingTasks[$task.id] = @{
                    id = $task.id
                    name = $task.name
                    status = $task.status.status
                    url = $task.url
                }
                Write-Host "  Found: $($task.name) [$($task.status.status)]" -ForegroundColor Gray
            }
        }
    } catch {
        Write-Host "  Search failed: $_" -ForegroundColor Red
    }
}

Write-Host "  Total existing tasks found: $($existingTasks.Count)" -ForegroundColor Green
Write-Host ""

# Step 2: Create new tasks if needed
Write-Host "Step 2: Creating tasks for each platform..." -ForegroundColor Yellow

$createdTasks = @()

foreach ($platform in $platforms) {
    # Check if task already exists
    $exists = $false
    foreach ($existingTask in $existingTasks.Values) {
        if ($existingTask.name -like "*$($platform.name.Split(' ')[0])*") {
            Write-Host "  âœ" $platform.name" - Already exists: $($existingTask.name)" -ForegroundColor Green
            $createdTasks += @{
                id = $existingTask.id
                name = $existingTask.name
                url = $existingTask.url
                file = $platform.file
                created = $false
            }
            $exists = $true
            break
        }
    }

    if (-not $exists) {
        # Create new task
        $taskBody = @{
            name = $platform.name
            description = "$($platform.description)`n`n**Timeline:** $($platform.timeline)`n`n**Documentation:** See attached PDF for complete verification guide.`n`nGenerated by Jengo's Social Media API Setup Script"
            markdown_description = "$($platform.description)`n`n**Timeline:** $($platform.timeline)`n`n**Documentation:** See attached PDF for complete verification guide.`n`nGenerated by Jengo's Social Media API Setup Script"
            status = "to do"
            priority = if ($platform.priority -eq "high") { 2 } elseif ($platform.priority -eq "medium") { 3 } else { 4 }
            tags = @("api", "social-media", "integration", "verification")
        } | ConvertTo-Json -Depth 5

        try {
            $response = Invoke-RestMethod -Uri "$API_BASE/list/$LIST_ID/task" -Headers $headers -Method Post -Body $taskBody
            Write-Host "  ✅ Created: $($platform.name)" -ForegroundColor Green
            Write-Host "     URL: $($response.url)" -ForegroundColor Gray

            $createdTasks += @{
                id = $response.id
                name = $response.name
                url = $response.url
                file = $platform.file
                created = $true
            }
        } catch {
            Write-Host "  ❌ Failed to create $($platform.name): $_" -ForegroundColor Red
        }
    }
}

Write-Host ""

# Step 3: Convert HTML to PDF (if needed)
Write-Host "Step 3: Checking for PDF files..." -ForegroundColor Yellow

$pdfsMissing = @()
foreach ($platform in $platforms) {
    $pdfPath = "C:\scripts\temp\$($platform.file).pdf"
    if (-not (Test-Path $pdfPath)) {
        $pdfsMissing += $platform.file
        Write-Host "  ⚠️  Missing: $($platform.file).pdf" -ForegroundColor Yellow
    } else {
        $size = (Get-Item $pdfPath).Length / 1KB
        Write-Host "  ✅ Found: $($platform.file).pdf ($([math]::Round($size, 1)) KB)" -ForegroundColor Green
    }
}

if ($pdfsMissing.Count -gt 0) {
    Write-Host ""
    Write-Host "⚠️  PDFs need to be created manually:" -ForegroundColor Yellow
    Write-Host "   1. The HTML files are already open in your browser" -ForegroundColor White
    Write-Host "   2. For each tab: Press Ctrl+P" -ForegroundColor White
    Write-Host "   3. Select 'Microsoft Print to PDF' or 'Save as PDF'" -ForegroundColor White
    Write-Host "   4. Save as: C:\scripts\temp\[filename].pdf" -ForegroundColor White
    Write-Host ""
    Write-Host "   Missing PDFs:" -ForegroundColor White
    foreach ($file in $pdfsMissing) {
        Write-Host "   - $file.pdf" -ForegroundColor Gray
    }
    Write-Host ""

    $response = Read-Host "Have you created the PDFs? (y/n)"
    if ($response -ne "y") {
        Write-Host ""
        Write-Host "Pausing script. Run again after creating PDFs." -ForegroundColor Yellow
        Write-Host "Script location: C:\scripts\temp\setup-social-media-api-tasks.ps1" -ForegroundColor Gray
        exit
    }
}

Write-Host ""

# Step 4: Upload PDFs to tasks
Write-Host "Step 4: Uploading PDFs to ClickUp tasks..." -ForegroundColor Yellow

foreach ($task in $createdTasks) {
    $pdfPath = "C:\scripts\temp\$($task.file).pdf"

    if (-not (Test-Path $pdfPath)) {
        Write-Host "  ⚠️  Skipping $($task.name) - PDF not found" -ForegroundColor Yellow
        continue
    }

    Write-Host "  Uploading to: $($task.name)..." -NoNewline

    try {
        # ClickUp requires multipart/form-data for file uploads
        $fileBytes = [System.IO.File]::ReadAllBytes($pdfPath)
        $fileContent = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetString($fileBytes)
        $boundary = [System.Guid]::NewGuid().ToString()

        $bodyLines = @(
            "--$boundary",
            "Content-Disposition: form-data; name=`"attachment`"; filename=`"$($task.file).pdf`"",
            "Content-Type: application/pdf",
            "",
            $fileContent,
            "--$boundary--"
        )

        $body = $bodyLines -join "`r`n"

        $uploadHeaders = @{
            "Authorization" = $API_KEY
            "Content-Type" = "multipart/form-data; boundary=$boundary"
        }

        $response = Invoke-RestMethod -Uri "$API_BASE/task/$($task.id)/attachment" `
            -Headers $uploadHeaders `
            -Method Post `
            -Body $body

        Write-Host " ✅ Done" -ForegroundColor Green
    } catch {
        Write-Host " ❌ Failed: $_" -ForegroundColor Red
        Write-Host "     Trying alternative upload method..." -ForegroundColor Gray

        # Alternative: Add comment with instruction to attach manually
        try {
            $commentBody = @{
                comment_text = "📎 **Verification Guide PDF:** Please attach the file C:\scripts\temp\$($task.file).pdf to this task."
            } | ConvertTo-Json

            Invoke-RestMethod -Uri "$API_BASE/task/$($task.id)/comment" `
                -Headers $headers `
                -Method Post `
                -Body $commentBody | Out-Null

            Write-Host "     ✅ Added comment with manual upload instruction" -ForegroundColor Green
        } catch {
            Write-Host "     ❌ Could not add comment either: $_" -ForegroundColor Red
        }
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Tasks created/updated: $($createdTasks.Count)" -ForegroundColor Green
Write-Host ""
Write-Host "ClickUp Tasks:" -ForegroundColor White
foreach ($task in $createdTasks) {
    $status = if ($task.created) { "✨ NEW" } else { "✓ EXISTS" }
    Write-Host "  $status - $($task.name)" -ForegroundColor $(if ($task.created) { "Green" } else { "Gray" })
    Write-Host "           $($task.url)" -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "✅ Done! Check ClickUp: https://app.clickup.com/9012956001/v/li/901214097647" -ForegroundColor Green
