# AI Test Generation
# Generates unit tests for C# code using Claude
#
# Usage:
#   .\generate-tests.ps1 -FilePath Services/UserService.cs
#   .\generate-tests.ps1 -FilePath Controllers/AuthController.cs -OutputPath Tests/
#   .\generate-tests.ps1 -Directory Services/ -Pattern "*.cs"

param(
    [Parameter(Mandatory=$false)]
    [string]$FilePath,

    [Parameter(Mandatory=$false)]
    [string]$Directory,

    [Parameter(Mandatory=$false)]
    [string]$Pattern = "*.cs",

    [Parameter(Mandatory=$false)]
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

if (-not $FilePath -and -not $Directory) {
    Write-Host "❌ Must specify either -FilePath or -Directory" -ForegroundColor Red
    exit 1
}

Write-Host "`n🧪 AI Test Generation" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Get files to process
$files = @()

if ($FilePath) {
    if (Test-Path $FilePath) {
        $files += Get-Item $FilePath
    } else {
        Write-Host "❌ File not found: $FilePath" -ForegroundColor Red
        exit 1
    }
}

if ($Directory) {
    if (Test-Path $Directory) {
        $files += Get-ChildItem -Path $Directory -Filter $Pattern -Recurse
    } else {
        Write-Host "❌ Directory not found: $Directory" -ForegroundColor Red
        exit 1
    }
}

Write-Host "📁 Found $($files.Count) file(s) to process" -ForegroundColor Gray
Write-Host ""

foreach ($file in $files) {
    Write-Host "📝 Processing: $($file.Name)" -ForegroundColor Yellow

    # Read source code
    $sourceCode = Get-Content $file.FullName -Raw

    # Determine test file path
    if ($OutputPath) {
        $testFileName = "$($file.BaseName)Tests.cs"
        $testFilePath = Join-Path $OutputPath $testFileName
    } else {
        # Auto-detect test directory
        $projectRoot = $file.DirectoryName
        while ($projectRoot -and -not (Test-Path "$projectRoot\*.csproj")) {
            $projectRoot = Split-Path $projectRoot -Parent
        }

        if ($projectRoot) {
            $testProject = Get-ChildItem "$projectRoot\.." -Filter "*.Tests.csproj" -Recurse | Select-Object -First 1
            if ($testProject) {
                $testDir = $testProject.DirectoryName
                $relativePath = $file.DirectoryName.Substring($projectRoot.Length).TrimStart('\')
                $testSubDir = Join-Path $testDir $relativePath

                if (-not (Test-Path $testSubDir)) {
                    New-Item -ItemType Directory -Path $testSubDir -Force | Out-Null
                }

                $testFileName = "$($file.BaseName)Tests.cs"
                $testFilePath = Join-Path $testSubDir $testFileName
            }
        }
    }

    if (-not $testFilePath) {
        Write-Host "   ⚠️ Could not determine test file path, skipping" -ForegroundColor Yellow
        continue
    }

    # Generate test template (AI generation would use Claude API here)
    # For MVP, creating a structured template

    Write-Host "   🤖 Generating test template..." -ForegroundColor Gray

    # Extract class name
    $classMatch = [regex]::Match($sourceCode, "class\s+(\w+)")
    $className = if ($classMatch.Success) { $classMatch.Groups[1].Value } else { $file.BaseName }

    # Extract methods
    $methodMatches = [regex]::Matches($sourceCode, "(?:public|private|protected|internal)\s+(?:async\s+)?(?:Task<?[\w<>]+>?|[\w<>]+)\s+(\w+)\s*\(")
    $methods = $methodMatches | ForEach-Object { $_.Groups[1].Value } | Where-Object { $_ -notmatch "^(get_|set_)" }

    # Extract namespace
    $namespaceMatch = [regex]::Match($sourceCode, "namespace\s+([\w.]+)")
    $namespace = if ($namespaceMatch.Success) { $namespaceMatch.Groups[1].Value } else { "Tests" }

    # Generate test code
    $testCode = @"
using Xunit;
using Moq;
using FluentAssertions;
using $namespace;

namespace ${namespace}.Tests
{
    /// <summary>
    /// Tests for $className
    /// Generated by AI Test Generation tool
    /// </summary>
    public class ${className}Tests
    {
        private readonly ${className} _sut;
        // Add mocks here as needed

        public ${className}Tests()
        {
            // TODO: Initialize system under test
            // _sut = new ${className}();
        }

"@

    foreach ($method in $methods) {
        $testCode += @"

        [Fact]
        public async Task ${method}_WhenCalled_ShouldReturnExpectedResult()
        {
            // Arrange
            // TODO: Set up test data and mocks

            // Act
            // TODO: Call the method under test
            // var result = await _sut.${method}();

            // Assert
            // TODO: Verify the result
            // result.Should().NotBeNull();
        }

        [Fact]
        public async Task ${method}_WhenInvalidInput_ShouldThrowException()
        {
            // Arrange
            // TODO: Set up invalid input

            // Act & Assert
            // await Assert.ThrowsAsync<ArgumentException>(() => _sut.${method}());
        }

"@
    }

    $testCode += @"
    }
}
"@

    # Write test file
    $testCode | Out-File -FilePath $testFilePath -Encoding UTF8

    Write-Host "   ✅ Generated: $testFilePath" -ForegroundColor Green
    Write-Host "   📊 Methods: $($methods.Count)" -ForegroundColor Gray
    Write-Host ""
}

Write-Host "🎉 Test generation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "💡 Next steps:" -ForegroundColor Yellow
Write-Host "   1. Review generated tests and fill in TODO sections" -ForegroundColor White
Write-Host "   2. Add necessary mocks and test data" -ForegroundColor White
Write-Host "   3. Run tests: dotnet test" -ForegroundColor White
Write-Host ""
Write-Host "🚀 Future: Full AI generation will write complete tests with edge cases" -ForegroundColor DarkYellow
