<#
.SYNOPSIS
    Auto-PR Generator
    50-Expert Council V2 Improvement #12 | Priority: 2.25

.DESCRIPTION
    Generates formatted PR from commits with description.
    Auto-detects PR type, scope, and creates checklist.

.PARAMETER Generate
    Generate PR description.

.PARAMETER Create
    Create the PR on GitHub.

.PARAMETER Base
    Base branch (default: develop).

.PARAMETER Draft
    Create as draft PR.

.EXAMPLE
    auto-pr.ps1 -Generate
    auto-pr.ps1 -Create -Base develop
#>

param(
    [switch]$Generate,
    [switch]$Create,
    [string]$Base = "develop",
    [switch]$Draft,
    [string]$RepoPath = "."
)

# AUTO-USAGE TRACKING
$toolName = $MyInvocation.MyCommand.Name -replace '\.ps1$', ''
. "$PSScriptRoot\_usage-logger.ps1" -ToolName $toolName -Action "execute" -Metadata @{ Parameters = ($PSBoundParameters.Keys -join ',') } -ErrorAction SilentlyContinue


function Analyze-Commits {
    param([string]$Base, [string]$RepoPath)

    Push-Location $RepoPath

    $currentBranch = git branch --show-current
    $commits = git log "$Base..$currentBranch" --pretty=format:"%s|%b" 2>&1

    $analysis = @{
        branch = $currentBranch
        type = "chore"
        scope = ""
        commits = @()
        changes = @{
            feat = 0
            fix = 0
            docs = 0
            refactor = 0
            test = 0
            other = 0
        }
        files = @()
    }

    # Get changed files
    $analysis.files = git diff "$Base..HEAD" --name-only 2>&1

    foreach ($commit in ($commits -split "`n")) {
        if (-not $commit) { continue }

        $parts = $commit -split '\|'
        $subject = $parts[0]

        $analysis.commits += $subject

        # Categorize
        if ($subject -match '^feat') { $analysis.changes.feat++ }
        elseif ($subject -match '^fix') { $analysis.changes.fix++ }
        elseif ($subject -match '^docs') { $analysis.changes.docs++ }
        elseif ($subject -match '^refactor') { $analysis.changes.refactor++ }
        elseif ($subject -match '^test') { $analysis.changes.test++ }
        else { $analysis.changes.other++ }
    }

    # Determine PR type
    if ($analysis.changes.feat -gt 0) { $analysis.type = "feat" }
    elseif ($analysis.changes.fix -gt 0) { $analysis.type = "fix" }
    elseif ($analysis.changes.docs -gt 0) { $analysis.type = "docs" }
    elseif ($analysis.changes.refactor -gt 0) { $analysis.type = "refactor" }

    # Extract scope from branch name
    if ($currentBranch -match 'feature/([^/]+)' -or $currentBranch -match 'fix/([^/]+)') {
        $analysis.scope = $matches[1]
    }

    Pop-Location
    return $analysis
}

function Generate-PRDescription {
    param($Analysis)

    $typeEmoji = switch ($Analysis.type) {
        "feat" { "✨" }
        "fix" { "🐛" }
        "docs" { "📚" }
        "refactor" { "♻️" }
        "test" { "🧪" }
        default { "🔧" }
    }

    $title = "$($Analysis.type)"
    if ($Analysis.scope) { $title += "($($Analysis.scope))" }
    $title += ": "

    # Generate title from first commit or branch
    if ($Analysis.commits.Count -gt 0) {
        $firstCommit = $Analysis.commits[0] -replace '^(feat|fix|docs|refactor|test|chore)(\([^)]+\))?:\s*', ''
        $title += $firstCommit
    }
    else {
        $title += $Analysis.branch -replace 'feature/|fix/|', ''
    }

    $body = @"
## $typeEmoji Summary

<!-- Brief description of what this PR does -->

## Changes

"@

    # List commits
    foreach ($commit in $Analysis.commits | Select-Object -First 10) {
        $body += "- $commit`n"
    }

    if ($Analysis.commits.Count -gt 10) {
        $body += "- ... and $($Analysis.commits.Count - 10) more commits`n"
    }

    $body += @"

## Files Changed

$($Analysis.files.Count) files modified

"@

    # Group files by directory
    $dirs = $Analysis.files | ForEach-Object { Split-Path $_ } | Select-Object -Unique | Select-Object -First 5
    foreach ($dir in $dirs) {
        $body += "- ``$dir/``*`n"
    }

    $body += @"

## Checklist

- [ ] Code follows project conventions
- [ ] Tests pass locally
- [ ] Documentation updated (if needed)
- [ ] No breaking changes (or documented)

## Testing

<!-- How to test this PR -->

---
*Generated by auto-pr.ps1*
"@

    return @{
        title = $title
        body = $body
    }
}

if ($Generate -or $Create) {
    Write-Host "=== AUTO-PR GENERATOR ===" -ForegroundColor Cyan
    Write-Host ""

    $analysis = Analyze-Commits -Base $Base -RepoPath $RepoPath

    Write-Host "Branch: $($analysis.branch)" -ForegroundColor Yellow
    Write-Host "Base: $Base" -ForegroundColor Gray
    Write-Host "Commits: $($analysis.commits.Count)" -ForegroundColor White
    Write-Host "Files: $($analysis.files.Count)" -ForegroundColor White
    Write-Host ""

    $pr = Generate-PRDescription $analysis

    Write-Host "Generated PR:" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "Title: $($pr.title)" -ForegroundColor Green
    Write-Host ""
    Write-Host "Body preview:" -ForegroundColor Yellow
    Write-Host ($pr.body | Select-Object -First 20 | Out-String) -ForegroundColor Gray
    Write-Host ""

    if ($Create) {
        Push-Location $RepoPath

        # Push branch first
        Write-Host "Pushing branch..." -ForegroundColor Yellow
        git push -u origin $analysis.branch 2>&1 | Out-Null

        # Create PR
        $draftFlag = if ($Draft) { "--draft" } else { "" }

        $cmd = "gh pr create --title `"$($pr.title)`" --body `"$($pr.body -replace '"', '\"')`" --base $Base $draftFlag"

        Write-Host "Creating PR..." -ForegroundColor Yellow
        $result = Invoke-Expression $cmd 2>&1

        if ($result -match 'https://github.com') {
            Write-Host ""
            Write-Host "✓ PR Created!" -ForegroundColor Green
            Write-Host "  $result" -ForegroundColor Cyan
        }
        else {
            Write-Host "Result: $result" -ForegroundColor Yellow
        }

        Pop-Location
    }
    else {
        Write-Host "To create: auto-pr.ps1 -Create -Base $Base" -ForegroundColor Gray
    }
}
else {
    Write-Host "Usage:" -ForegroundColor Yellow
    Write-Host "  -Generate             Preview PR" -ForegroundColor White
    Write-Host "  -Create               Create PR on GitHub" -ForegroundColor White
    Write-Host "  -Base develop         Set base branch" -ForegroundColor White
    Write-Host "  -Draft                Create as draft" -ForegroundColor White
}
