<#
.SYNOPSIS
    Mistake → Prevention Pipeline - Auto-generates prevention rules from errors.
    50-Expert Council Improvement #22 | Priority: 2.0

.DESCRIPTION
    When a mistake is logged, this tool:
    1. Extracts the error pattern
    2. Creates a prevention rule
    3. Adds to error_prevention.json
    4. Optionally creates a pre-commit hook

.PARAMETER Mistake
    Description of the mistake that occurred.

.PARAMETER Cause
    Root cause of the mistake.

.PARAMETER Prevention
    How to prevent it in the future.

.PARAMETER Severity
    CRITICAL, HIGH, MEDIUM, LOW

.PARAMETER CreateHook
    Create a pre-commit hook to prevent this.

.EXAMPLE
    mistake-to-prevention.ps1 -Mistake "Edited base repo directly" -Cause "Forgot to allocate worktree" -Prevention "Always check worktree status first" -Severity HIGH
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$Mistake,

    [string]$Cause = "",

    [string]$Prevention = "",

    [ValidateSet("CRITICAL", "HIGH", "MEDIUM", "LOW")]
    [string]$Severity = "MEDIUM",

    [switch]$CreateHook
)
# AUTO-USAGE TRACKING
$toolName = $MyInvocation.MyCommand.Name -replace '\.ps1$', ''
. "$PSScriptRoot\_usage-logger.ps1" -ToolName $toolName -Action "execute" -Metadata @{ Parameters = ($PSBoundParameters.Keys -join ',') } -ErrorAction SilentlyContinue

$PreventionDB = "C:\scripts\_machine\error_prevention.json"
$ReflectionLog = "C:\scripts\_machine\reflection.log.md"
$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

Write-Host "=== MISTAKE → PREVENTION PIPELINE ===" -ForegroundColor Cyan
Write-Host ""

# Load or create database
if (Test-Path $PreventionDB) {
    $db = Get-Content $PreventionDB -Raw | ConvertFrom-Json
} else {
    $db = @{
        patterns = @()
        learnedPatterns = @()
        lastScan = $null
        preventionCount = 0
    }
}

# Generate pattern from mistake
$patternWords = ($Mistake -split '\s+' | Where-Object { $_.Length -gt 3 } | Select-Object -First 3) -join '.*'
$pattern = "(?i)$patternWords"

Write-Host "Mistake: $Mistake" -ForegroundColor Red
Write-Host "Cause: $Cause" -ForegroundColor Yellow
Write-Host "Generated pattern: $pattern" -ForegroundColor Gray
Write-Host ""

# Create prevention entry
$newPrevention = @{
    pattern = $pattern
    error = $Mistake
    cause = $Cause
    prevention = if ($Prevention) { $Prevention } else { "Review and apply caution before: $Mistake" }
    severity = $Severity
    created = $Timestamp
    source = "mistake-to-prevention pipeline"
}

# Add to learned patterns
$db.learnedPatterns += $newPrevention
$db | ConvertTo-Json -Depth 10 | Set-Content $PreventionDB -Encoding UTF8

Write-Host "✓ Prevention rule created:" -ForegroundColor Green
Write-Host "  Severity: $Severity" -ForegroundColor $(if ($Severity -eq "CRITICAL") { "Red" } elseif ($Severity -eq "HIGH") { "Yellow" } else { "White" })
Write-Host "  Prevention: $($newPrevention.prevention)" -ForegroundColor White
Write-Host ""

# Log to reflection
$reflectionEntry = @"

---
### Mistake Logged - $Timestamp

**Mistake:** $Mistake
**Cause:** $Cause
**Severity:** $Severity
**Prevention Rule Created:** $($newPrevention.prevention)
**Pattern:** ``$pattern``

*Auto-generated by mistake-to-prevention.ps1 (50-Expert Council #22)*

"@

if (Test-Path $ReflectionLog) {
    Add-Content -Path $ReflectionLog -Value $reflectionEntry -Encoding UTF8
    Write-Host "✓ Logged to reflection.log.md" -ForegroundColor Green
}

# Create pre-commit hook if requested
if ($CreateHook) {
    $hookScript = @"
# Prevention hook for: $Mistake
# Generated: $Timestamp

`$errorPattern = "$pattern"
`$stagedFiles = git diff --cached --name-only

foreach (`$file in `$stagedFiles) {
    if (`$file -match `$errorPattern) {
        Write-Host "BLOCKED: $Mistake" -ForegroundColor Red
        Write-Host "Prevention: $($newPrevention.prevention)" -ForegroundColor Yellow
        exit 1
    }
}
"@

    $hookPath = "C:\scripts\hooks\prevent_$($Mistake -replace '\s+', '_' -replace '[^a-zA-Z0-9_]', '').ps1"
    $hookDir = Split-Path $hookPath -Parent
    if (-not (Test-Path $hookDir)) { New-Item -ItemType Directory -Path $hookDir -Force | Out-Null }

    Set-Content -Path $hookPath -Value $hookScript -Encoding UTF8
    Write-Host "✓ Pre-commit hook created: $hookPath" -ForegroundColor Green
}

Write-Host ""
Write-Host "Pipeline complete. Future actions matching this pattern will trigger warnings." -ForegroundColor Magenta
Write-Host ""
Write-Host "Test with: prevent-errors.ps1 -Action `"$Mistake`"" -ForegroundColor Gray
