<#
.SYNOPSIS
    Success → Amplification Pipeline - Every win generates replication pattern.
    50-Expert Council Improvement #23 | Priority: 2.25

.DESCRIPTION
    When something works well, capture it as a reusable pattern.
    Builds institutional knowledge from successes.

.PARAMETER Success
    Description of what succeeded.

.PARAMETER Context
    Context where it succeeded.

.PARAMETER Pattern
    Generalizable pattern extracted.

.PARAMETER Tags
    Comma-separated tags for searchability.

.EXAMPLE
    success-to-pattern.ps1 -Success "PR created in 5 minutes" -Context "Used workflow.ps1" -Pattern "One-command workflows save time" -Tags "workflow,efficiency,pr"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$Success,

    [string]$Context = "",

    [string]$Pattern = "",

    [string]$Tags = ""
)
# AUTO-USAGE TRACKING
$toolName = $MyInvocation.MyCommand.Name -replace '\.ps1$', ''
. "$PSScriptRoot\_usage-logger.ps1" -ToolName $toolName -Action "execute" -Metadata @{ Parameters = ($PSBoundParameters.Keys -join ',') } -ErrorAction SilentlyContinue

$PatternLibrary = "C:\scripts\_machine\pattern_library.json"
$ReflectionLog = "C:\scripts\_machine\reflection.log.md"
$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

Write-Host "=== SUCCESS → AMPLIFICATION PIPELINE ===" -ForegroundColor Green
Write-Host ""

# Load or create pattern library
if (Test-Path $PatternLibrary) {
    $library = Get-Content $PatternLibrary -Raw | ConvertFrom-Json
} else {
    $library = @{
        patterns = @()
        tags = @{}
        successCount = 0
    }
}

# Parse tags
$tagList = if ($Tags) { $Tags -split ',' | ForEach-Object { $_.Trim() } } else { @("general") }

# Create pattern entry
$newPattern = @{
    id = [guid]::NewGuid().ToString().Substring(0, 8)
    success = $Success
    context = $Context
    pattern = if ($Pattern) { $Pattern } else { "Success pattern: $Success" }
    tags = $tagList
    created = $Timestamp
    useCount = 0
    source = "success-to-pattern pipeline"
}

# Add to library
$library.patterns += $newPattern
$library.successCount++

# Update tag index
foreach ($tag in $tagList) {
    if (-not $library.tags.$tag) {
        $library.tags | Add-Member -NotePropertyName $tag -NotePropertyValue @() -Force
    }
    $library.tags.$tag += $newPattern.id
}

$library | ConvertTo-Json -Depth 10 | Set-Content $PatternLibrary -Encoding UTF8

Write-Host "Success: $Success" -ForegroundColor Green
Write-Host "Context: $Context" -ForegroundColor Yellow
Write-Host "Pattern: $($newPattern.pattern)" -ForegroundColor Cyan
Write-Host "Tags: $($tagList -join ', ')" -ForegroundColor Gray
Write-Host ""
Write-Host "✓ Pattern saved to library (ID: $($newPattern.id))" -ForegroundColor Green
Write-Host "Total success patterns: $($library.successCount)" -ForegroundColor Magenta

# Log to reflection
$reflectionEntry = @"

---
### Success Logged - $Timestamp

**Success:** $Success
**Context:** $Context
**Pattern Extracted:** $($newPattern.pattern)
**Tags:** $($tagList -join ', ')

*Auto-generated by success-to-pattern.ps1 (50-Expert Council #23)*

"@

if (Test-Path $ReflectionLog) {
    Add-Content -Path $ReflectionLog -Value $reflectionEntry -Encoding UTF8
    Write-Host "✓ Logged to reflection.log.md" -ForegroundColor Green
}

Write-Host ""
Write-Host "Search with: pattern-library.ps1 -Search '$($tagList[0])'" -ForegroundColor Gray
