# Automated Tool Scheduler
# Schedule recurring scans and audits

param(
    [switch]$Install,
    [switch]$Uninstall,
    [switch]$ShowSchedule,
    [switch]$RunNow
)

$taskBaseName = "Jengo-Automated"

function Install-Schedules {
    Write-Host "📅 Installing automated schedules..." -ForegroundColor Cyan

    # Weekly Sunday 2 AM: Tool usage analytics + doc pruning
    $weeklyAction = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -File C:\scripts\tools\weekly-maintenance.ps1"
    $weeklyTrigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Sunday -At 2am
    $weeklySettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

    Register-ScheduledTask -TaskName "$taskBaseName-Weekly" -Action $weeklyAction -Trigger $weeklyTrigger -Settings $weeklySettings -Description "Weekly tool/doc health maintenance" -Force | Out-Null

    Write-Host "  ✅ Weekly maintenance (Sunday 2 AM)" -ForegroundColor Green

    # Daily 8 AM: Proactive problem scan
    $dailyAction = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -File C:\scripts\tools\daily-health-check.ps1"
    $dailyTrigger = New-ScheduledTaskTrigger -Daily -At 8am
    $dailySettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

    Register-ScheduledTask -TaskName "$taskBaseName-Daily" -Action $dailyAction -Trigger $dailyTrigger -Settings $dailySettings -Description "Daily proactive problem scan" -Force | Out-Null

    Write-Host "  ✅ Daily health check (8 AM)" -ForegroundColor Green

    # Create the scheduled scripts if they don't exist
    Create-ScheduledScripts

    Write-Host "`n✅ Automated schedules installed successfully" -ForegroundColor Green
    Write-Host "   View with: .\automated-scheduler.ps1 -ShowSchedule" -ForegroundColor Gray
}

function Create-ScheduledScripts {
    # Weekly maintenance script
    $weeklyScript = @'
# Weekly Maintenance Script
# Auto-generated by automated-scheduler.ps1

$logFile = "C:\scripts\_machine\weekly-maintenance.log"

"=== Weekly Maintenance: $(Get-Date -Format 'yyyy-MM-dd HH:mm') ===" | Out-File $logFile -Append

# Tool usage analytics
Write-Host "Running tool usage analytics..."
& "C:\scripts\tools\tool-usage-analytics.ps1" -Scan
$result = & "C:\scripts\tools\tool-usage-analytics.ps1" -Report
$result | Out-File $logFile -Append

# Documentation health
Write-Host "Running documentation health scan..."
$result = & "C:\scripts\tools\doc-pruning.ps1" -Analyze
$result | Out-File $logFile -Append

# Value alignment summary
if (Test-Path "C:\scripts\tools\value-alignment-audit.ps1") {
    Write-Host "Generating value alignment report..."
    $result = & "C:\scripts\tools\value-alignment-audit.ps1" -Report
    $result | Out-File $logFile -Append
}

"=== Weekly Maintenance Complete ===" | Out-File $logFile -Append

Write-Host "Weekly maintenance complete. Log: $logFile"
'@

    $weeklyScript | Set-Content "C:\scripts\tools\weekly-maintenance.ps1" -Force

    # Daily health check script
    $dailyScript = @'
# Daily Health Check Script
# Auto-generated by automated-scheduler.ps1

$logFile = "C:\scripts\_machine\daily-health-check.log"
$dateStamp = Get-Date -Format 'yyyy-MM-dd HH:mm'

"=== Daily Health Check: $dateStamp ===" | Out-File $logFile -Append

# Proactive problem scan
Write-Host "Running proactive problem scan..."
& "C:\scripts\tools\proactive-problem-scan.ps1" -Scan

$result = & "C:\scripts\tools\proactive-problem-scan.ps1" -Report
$result | Out-File $logFile -Append

# Check for high-severity issues
$scanResults = Get-Content "C:\scripts\_machine\proactive-scan-results.json" | ConvertFrom-Json

if ($scanResults.summary.high -gt 0) {
    Write-Host "⚠️ HIGH SEVERITY ISSUES FOUND: $($scanResults.summary.high)" -ForegroundColor Red

    # Log to alert file for dashboard pickup
    $alertFile = "C:\scripts\_machine\alerts.json"
    $alert = @{
        timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
        severity = "high"
        message = "$($scanResults.summary.high) high-severity issues detected"
        issues = $scanResults.issues | Where-Object { $_.severity -eq "high" }
    } | ConvertTo-Json -Depth 10

    $alert | Set-Content $alertFile
}

"=== Daily Health Check Complete ===" | Out-File $logFile -Append

Write-Host "Daily health check complete. Log: $logFile"
'@

    $dailyScript | Set-Content "C:\scripts\tools\daily-health-check.ps1" -Force

    Write-Host "  ✅ Created scheduled scripts" -ForegroundColor Green
}

function Remove-Schedules {
    Write-Host "🗑️ Uninstalling automated schedules..." -ForegroundColor Yellow

    $tasks = Get-ScheduledTask -TaskName "$taskBaseName-*" -ErrorAction SilentlyContinue

    foreach ($task in $tasks) {
        Unregister-ScheduledTask -TaskName $task.TaskName -Confirm:$false
        Write-Host "  ✅ Removed: $($task.TaskName)" -ForegroundColor Green
    }

    Write-Host "`n✅ Automated schedules uninstalled" -ForegroundColor Green
}

function Show-CurrentSchedule {
    Write-Host "`n═══════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "📅 AUTOMATED SCHEDULE" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan

    $tasks = Get-ScheduledTask -TaskName "$taskBaseName-*" -ErrorAction SilentlyContinue

    if ($tasks.Count -eq 0) {
        Write-Host "`n⚠️ No automated schedules installed" -ForegroundColor Yellow
        Write-Host "   Run with -Install to set up automation" -ForegroundColor Gray
    }
    else {
        Write-Host "`nINSTALLED TASKS:`n"

        foreach ($task in $tasks) {
            $info = Get-ScheduledTaskInfo -TaskName $task.TaskName
            $lastRun = if ($info.LastRunTime.Year -gt 1900) { $info.LastRunTime.ToString("yyyy-MM-dd HH:mm") } else { "Never" }
            $nextRun = if ($info.NextRunTime.Year -gt 1900) { $info.NextRunTime.ToString("yyyy-MM-dd HH:mm") } else { "Not scheduled" }
            $status = $task.State

            $statusIcon = if ($status -eq "Ready") { "✅" } else { "⚠️" }

            Write-Host "$statusIcon $($task.TaskName)" -ForegroundColor Cyan
            Write-Host "   Description: $($task.Description)"
            Write-Host "   Status: $status"
            Write-Host "   Last run: $lastRun"
            Write-Host "   Next run: $nextRun"
            Write-Host ""
        }
    }

    Write-Host "═══════════════════════════════════════════════`n" -ForegroundColor Cyan
}

function Invoke-ImmediateRun {
    Write-Host "🚀 Running scheduled tasks immediately..." -ForegroundColor Cyan

    if (Test-Path "C:\scripts\tools\weekly-maintenance.ps1") {
        Write-Host "`n📊 Running weekly maintenance..." -ForegroundColor Yellow
        & "C:\scripts\tools\weekly-maintenance.ps1"
    }

    if (Test-Path "C:\scripts\tools\daily-health-check.ps1") {
        Write-Host "`n🔍 Running daily health check..." -ForegroundColor Yellow
        & "C:\scripts\tools\daily-health-check.ps1"
    }

    Write-Host "`n✅ Immediate run complete" -ForegroundColor Green
}

# Main execution
if ($Install) {
    Install-Schedules
}
elseif ($Uninstall) {
    Remove-Schedules
}
elseif ($ShowSchedule) {
    Show-CurrentSchedule
}
elseif ($RunNow) {
    Invoke-ImmediateRun
}
else {
    Write-Host "AUTOMATED TOOL SCHEDULER" -ForegroundColor Cyan
    Write-Host "Usage:"
    Write-Host "  Install schedules: .\automated-scheduler.ps1 -Install"
    Write-Host "  Show schedule: .\automated-scheduler.ps1 -ShowSchedule"
    Write-Host "  Run now: .\automated-scheduler.ps1 -RunNow"
    Write-Host "  Uninstall: .\automated-scheduler.ps1 -Uninstall"
    Write-Host ""
    Write-Host "Schedules:"
    Write-Host "  • Weekly (Sunday 2 AM): Tool/doc health maintenance"
    Write-Host "  • Daily (8 AM): Proactive problem scan"
}
