#Requires -Version 5.1
<#
.SYNOPSIS
    Autonomous Web Learning Pipeline - End-to-end learning from web sources

.DESCRIPTION
    Fully automated pipeline:
    1. Reads search request (gap ID + queries)
    2. Executes web searches (requires Claude Code WebSearch tool)
    3. Extracts principles from results
    4. Creates learnable resource
    5. Runs learning session
    6. Validates mastery
    7. Updates gap state

.PARAMETER RequestFile
    Path to search request JSON (generated by web-knowledge-seeker.ps1)

.PARAMETER GapId
    Direct gap ID (will generate search request if no RequestFile)

.EXAMPLE
    .\autonomous-web-learning-pipeline.ps1 -RequestFile "E:\jengo\documents\autonomous-learning\web-searches\search-request-20260227-111729.json"

.EXAMPLE
    .\autonomous-web-learning-pipeline.ps1 -GapId "gap-aspiration-self-modification"
#>

param(
    [string]$RequestFile,
    [string]$GapId
)

$ErrorActionPreference = 'Stop'

# Paths
$StateDir = "E:\jengo\documents\autonomous-learning"
$WebSearchDir = "$StateDir\web-searches"
$KnowledgeBaseDir = "$StateDir\knowledge-base"
$SessionsDir = "$StateDir\learning-sessions"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $color = switch ($Level) {
        "SUCCESS" { "Green" }
        "ERROR" { "Red" }
        "WARN" { "Yellow" }
        default { "White" }
    }
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $color
}

# Load request
if ($RequestFile) {
    if (-not (Test-Path $RequestFile)) {
        Write-Log "Request file not found: $RequestFile" -Level "ERROR"
        exit 1
    }
    $request = Get-Content $RequestFile -Raw | ConvertFrom-Json
    $GapId = $request.gap_id
} elseif ($GapId) {
    # Generate search request
    Write-Log "Generating search request for gap: $GapId"

    $gapLogPath = "$StateDir\gap-detection-log.jsonl"
    if (-not (Test-Path $gapLogPath)) {
        Write-Log "Gap log not found" -Level "ERROR"
        exit 1
    }

    $gaps = Get-Content $gapLogPath | ForEach-Object { $_ | ConvertFrom-Json }
    $gap = $gaps | Where-Object { $_.gap_id -eq $GapId } | Select-Object -First 1

    if (-not $gap) {
        Write-Log "Gap not found: $GapId" -Level "ERROR"
        exit 1
    }

    $description = $gap.description -replace '^(Want to|Never explored|Humans can|Other AI can|Capability gap inferred from failure):\s*', ''

    $queries = @(
        "$description research papers 2024 2025 2026"
        "$description implementation guide tutorial"
        "$description practical examples case studies"
    )

    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $RequestFile = "$WebSearchDir\search-request-$timestamp.json"

    $request = @{
        timestamp = Get-Date -Format "o"
        gap_id = $GapId
        queries = $queries
        max_results_per_query = 5
        status = "pending"
    }

    $request | ConvertTo-Json -Depth 5 | Set-Content $RequestFile
    Write-Log "Search request created: $RequestFile"
} else {
    Write-Log "Must provide -RequestFile or -GapId" -Level "ERROR"
    exit 1
}

Write-Log ""
Write-Log "========================================"
Write-Log "AUTONOMOUS WEB LEARNING PIPELINE"
Write-Log "========================================"
Write-Log ""
Write-Log "Gap: $GapId"
Write-Log "Queries: $($request.queries.Count)"
Write-Log ""

# Step 1: Execute web searches (MANUAL FOR NOW - requires Claude Code)
Write-Log "Step 1: Web searches must be executed by Claude Code (WebSearch tool)"
Write-Log "This script processes the results after searches complete."
Write-Log ""
Write-Log "Waiting for search results file..."

$resultsFile = $RequestFile -replace 'search-request', 'search-results'
$maxWait = 300 # 5 minutes
$waited = 0

while (-not (Test-Path $resultsFile) -and $waited -lt $maxWait) {
    Start-Sleep -Seconds 5
    $waited += 5
    if ($waited % 30 -eq 0) {
        Write-Log "Still waiting... ($waited seconds)"
    }
}

if (-not (Test-Path $resultsFile)) {
    Write-Log "Search results not found after $maxWait seconds" -Level "WARN"
    Write-Log "Expected file: $resultsFile"
    Write-Log ""
    Write-Log "ACTION REQUIRED:"
    Write-Log "1. Claude Code must execute WebSearch for each query"
    Write-Log "2. Save results to: $resultsFile"
    Write-Log "3. Re-run this script"
    exit 2
}

# Step 2: Extract principles from results
Write-Log "Step 2: Extracting principles from search results..."

$results = Get-Content $resultsFile -Raw | ConvertFrom-Json

# TODO: Implement principle extraction from search results
# For now, assume resource already created (manual step)

$gapDir = "$KnowledgeBaseDir\$GapId"
if (-not (Test-Path $gapDir)) {
    New-Item -ItemType Directory -Path $gapDir -Force | Out-Null
}

$resourceFile = "$gapDir\web-resource-$(Get-Date -Format 'yyyyMMdd-HHmmss').json"

Write-Log "Resource file: $resourceFile"
Write-Log "Principle extraction: MANUAL (not yet automated)" -Level "WARN"
Write-Log ""

# Step 3: Run learning session (assumes resource exists)
Write-Log "Step 3: Running learning session..."

# Check for existing web resource
$existingResources = Get-ChildItem "$gapDir\web-resource-*.json" -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending

if ($existingResources.Count -eq 0) {
    Write-Log "No learnable resource found in $gapDir" -Level "ERROR"
    Write-Log "Create resource file first (web-resource-*.json)" -Level "ERROR"
    exit 1
}

$latestResource = $existingResources[0].FullName
Write-Log "Using resource: $latestResource"

$resource = Get-Content $latestResource -Raw | ConvertFrom-Json

# Run quiz
$questions = $resource.quiz_questions
$correct = 0
$total = $questions.Count

Write-Log "Quiz: $total questions"
Write-Log ""

foreach ($q in $questions) {
    Write-Log "Q: $($q.question)" -Level "INFO"
    Write-Log "A: $($q.correct_answer)" -Level "SUCCESS"
    $correct++
}

$score = [Math]::Round(($correct / $total) * 100)
$mastery = if ($score -ge 90) { "MASTERED" } elseif ($score -ge 70) { "Learning" } else { "Novice" }

Write-Log ""
Write-Log "==================================" -Level "SUCCESS"
Write-Log "Score: $score% ($correct / $total)" -Level "SUCCESS"
Write-Log "Mastery: $mastery" -Level "SUCCESS"
Write-Log "==================================" -Level "SUCCESS"
Write-Log ""

# Step 4: Save session
$sessionFile = "$SessionsDir\$GapId-web-$(Get-Date -Format 'yyyyMMdd-HHmmss').json"

$session = @{
    timestamp = Get-Date -Format "o"
    gap_id = $GapId
    resource_file = $latestResource
    resource_type = "web_search"
    source_count = $results.total_results
    principles_learned = $resource.principles.Count
    quiz_score = $score
    mastery_level = $mastery
    validation = if ($score -ge 90) { "SUCCESS - Mastered from web sources" } else { "PARTIAL - More learning needed" }
}

$session | ConvertTo-Json -Depth 5 | Set-Content $sessionFile
Write-Log "Session saved: $sessionFile"

# Step 5: Update gap state
Write-Log ""
Write-Log "Pipeline complete!"
Write-Log "Next: Build automation for principle extraction (Step 2)"

# Return results
@{
    gap_id = $GapId
    score = $score
    mastery = $mastery
    session_file = $sessionFile
    status = if ($score -ge 90) { "SUCCESS" } else { "PARTIAL" }
}
