<#
.SYNOPSIS
    Auto-generate documentation from PowerShell scripts

.DESCRIPTION
    Scans PowerShell scripts in specified directory, extracts
    comment-based help, and generates comprehensive documentation.

    Extracts:
    - .SYNOPSIS
    - .DESCRIPTION
    - .PARAMETER
    - .EXAMPLE
    - .NOTES

.PARAMETER Path
    Directory to scan for .ps1 files (default: C:\scripts\tools)

.PARAMETER OutputPath
    Where to save generated documentation (default: C:\scripts\tools\AUTO_GENERATED_DOCS.md)

.EXAMPLE
    .\auto-document-scripts.ps1

.EXAMPLE
    .\auto-document-scripts.ps1 -Path "C:\scripts\tools" -OutputPath "tools-docs.md"
#>

param(
    [Parameter(Mandatory=$false)]
    [string]$Path = "C:\scripts\tools",

    [Parameter(Mandatory=$false)]
    [string]$OutputPath = "C:\scripts\tools\AUTO_GENERATED_DOCS.md"
)

$ErrorActionPreference = 'Stop'

Write-Host ""
Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  PowerShell Script Auto-Documenter" -ForegroundColor White
Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Get all PowerShell scripts
Write-Host "🔍 Scanning for PowerShell scripts in: $Path" -ForegroundColor Cyan
$scripts = Get-ChildItem -Path $Path -Filter "*.ps1" -File | Sort-Object Name

Write-Host "  Found $($scripts.Count) scripts" -ForegroundColor Gray
Write-Host ""

# Generate documentation
$doc = @"
# PowerShell Scripts Documentation

**Auto-generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**Source Directory:** ``$Path``
**Total Scripts:** $($scripts.Count)

---

## Table of Contents

"@

# Add table of contents
foreach ($script in $scripts) {
    $name = $script.Name
    $anchor = $name -replace '\.ps1$', '' -replace '[^a-zA-Z0-9-]', '-'
    $doc += "- [$name](#$anchor)`n"
}

$doc += "`n---`n`n"

# Document each script
foreach ($script in $scripts) {
    Write-Host "📝 Documenting: $($script.Name)" -ForegroundColor Cyan

    $content = Get-Content $script.FullName -Raw

    # Extract comment-based help
    $synopsis = ""
    $description = ""
    $parameters = @()
    $examples = @()
    $notes = ""

    if ($content -match '(?s)<#(.*?)#>') {
        $helpBlock = $Matches[1]

        # Extract SYNOPSIS
        if ($helpBlock -match '\.SYNOPSIS\s+(.*?)(?=\.|\z)') {
            $synopsis = $Matches[1].Trim()
        }

        # Extract DESCRIPTION
        if ($helpBlock -match '\.DESCRIPTION\s+(.*?)(?=\.|\z)') {
            $description = $Matches[1].Trim()
        }

        # Extract PARAMETERS
        $paramMatches = [regex]::Matches($helpBlock, '\.PARAMETER\s+(\w+)\s+(.*?)(?=\.|\z)')
        foreach ($match in $paramMatches) {
            $parameters += @{
                Name = $match.Groups[1].Value
                Description = $match.Groups[2].Value.Trim()
            }
        }

        # Extract EXAMPLES
        $exampleMatches = [regex]::Matches($helpBlock, '\.EXAMPLE\s+(.*?)(?=\.|\z)')
        foreach ($match in $exampleMatches) {
            $examples += $match.Groups[1].Value.Trim()
        }

        # Extract NOTES
        if ($helpBlock -match '\.NOTES\s+(.*?)(?=\.|\z)') {
            $notes = $Matches[1].Trim()
        }
    }

    # Build documentation section
    $anchor = $script.Name -replace '\.ps1$', '' -replace '[^a-zA-Z0-9-]', '-'
    $doc += "## $($script.Name)`n`n"

    if ($synopsis) {
        $doc += "**Synopsis:** $synopsis`n`n"
    }

    if ($description) {
        $doc += "### Description`n`n$description`n`n"
    }

    if ($parameters.Count -gt 0) {
        $doc += "### Parameters`n`n"
        foreach ($param in $parameters) {
            $doc += "- **$($param.Name)**: $($param.Description)`n"
        }
        $doc += "`n"
    }

    if ($examples.Count -gt 0) {
        $doc += "### Examples`n`n"
        foreach ($example in $examples) {
            $doc += "````powershell`n$example`n```````n`n"
        }
    }

    if ($notes) {
        $doc += "### Notes`n`n$notes`n`n"
    }

    # Add file metadata
    $doc += "**File:** ``$($script.FullName)```n"
    $doc += "**Last Modified:** $($script.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss"))`n"
    $doc += "**Size:** $([math]::Round($script.Length / 1KB, 2)) KB`n`n"

    $doc += "---`n`n"
}

$doc += "*Auto-generated by auto-document-scripts.ps1*`n"

# Save documentation
$doc | Set-Content $OutputPath -Encoding UTF8

Write-Host ""
Write-Host "✅ Documentation generated: $OutputPath" -ForegroundColor Green
Write-Host ""
Write-Host "📊 Statistics:" -ForegroundColor Cyan
Write-Host "  - Scripts documented: $($scripts.Count)" -ForegroundColor Gray
Write-Host "  - Total documentation lines: $($doc -split "`n" | Measure-Object | Select-Object -ExpandProperty Count)" -ForegroundColor Gray
Write-Host "  - Output size: $([math]::Round((Get-Item $OutputPath).Length / 1KB, 2)) KB" -ForegroundColor Gray
Write-Host ""
