<#
.SYNOPSIS
    Automatically document actions taken during agent sessions

.DESCRIPTION
    Reads conversation-events.log.jsonl and generates human-readable
    documentation of actions, decisions, and outcomes.

    Outputs:
    - Action timeline
    - Decision log
    - File modification summary
    - Command execution history

.PARAMETER SessionId
    Filter by specific session ID (optional)

.PARAMETER OutputPath
    Where to save the generated documentation

.EXAMPLE
    .\auto-document-actions.ps1 -OutputPath session-docs.md

.EXAMPLE
    .\auto-document-actions.ps1 -SessionId "2026-02-05T03:09:00" -OutputPath session.md
#>

param(
    [Parameter(Mandatory=$false)]
    [string]$SessionId,

    [Parameter(Mandatory=$true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

Write-Host ""
Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Action-to-Documentation Generator" -ForegroundColor White
Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

$EventLogPath = "C:\_machine\conversation-events.log.jsonl"

if (-not (Test-Path $EventLogPath)) {
    Write-Host "❌ Event log not found: $EventLogPath" -ForegroundColor Red
    exit 1
}

# Read and parse events
Write-Host "📖 Reading event log..." -ForegroundColor Cyan
$events = Get-Content $EventLogPath | ForEach-Object {
    $_ | ConvertFrom-Json
}

if ($SessionId) {
    $events = $events | Where-Object { $_.session_id -eq $SessionId }
}

Write-Host "  Found $($events.Count) events" -ForegroundColor Gray
Write-Host ""

# Group events by type
$fileEvents = $events | Where-Object { $_.event_type -eq 'file_operation' }
$commandEvents = $events | Where-Object { $_.event_type -eq 'command_execution' }
$decisionEvents = $events | Where-Object { $_.event_type -eq 'decision' }

# Generate documentation
$doc = @"
# Agent Session Documentation

**Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**Session:** $($SessionId ? $SessionId : "All sessions")
**Total Events:** $($events.Count)

---

## Summary

- File Operations: $($fileEvents.Count)
- Commands Executed: $($commandEvents.Count)
- Decisions Made: $($decisionEvents.Count)

---

## Timeline

"@

# Add timeline
foreach ($event in ($events | Sort-Object timestamp)) {
    $time = $event.timestamp
    $type = $event.event_type
    $details = $event.details

    $doc += "`n### $time - $type`n"
    $doc += "`n$details`n"
}

$doc += "`n---`n`n## File Operations`n`n"

foreach ($file in ($fileEvents | Sort-Object timestamp)) {
    $doc += "- **$($file.timestamp)**: $($file.operation) - ``$($file.file_path)```n"
}

$doc += "`n---`n`n## Commands Executed`n`n"

foreach ($cmd in ($commandEvents | Sort-Object timestamp)) {
    $doc += "- **$($cmd.timestamp)**: ``$($cmd.command)```n"
    if ($cmd.exit_code -ne 0) {
        $doc += "  - ⚠️ Exit code: $($cmd.exit_code)`n"
    }
}

$doc += "`n---`n`n## Decisions Made`n`n"

foreach ($decision in ($decisionEvents | Sort-Object timestamp)) {
    $doc += "### $($decision.timestamp)`n`n"
    $doc += "**Context:** $($decision.context)`n`n"
    $doc += "**Decision:** $($decision.decision)`n`n"
    $doc += "**Rationale:** $($decision.rationale)`n`n"
}

$doc += "`n---`n`n*Generated by auto-document-actions.ps1*`n"

# Save documentation
$doc | Set-Content $OutputPath -Encoding UTF8

Write-Host "✅ Documentation generated: $OutputPath" -ForegroundColor Green
Write-Host ""
Write-Host "📊 Statistics:" -ForegroundColor Cyan
Write-Host "  - Total lines: $($doc -split "`n" | Measure-Object | Select-Object -ExpandProperty Count)" -ForegroundColor Gray
Write-Host "  - File operations documented: $($fileEvents.Count)" -ForegroundColor Gray
Write-Host "  - Commands documented: $($commandEvents.Count)" -ForegroundColor Gray
Write-Host "  - Decisions documented: $($decisionEvents.Count)" -ForegroundColor Gray
Write-Host ""
