<#
.SYNOPSIS
    Generate deployment checklist for releases

.DESCRIPTION
    Creates comprehensive deployment checklists:
    - Environment-specific steps
    - Pre-deployment verification
    - Deployment procedure
    - Post-deployment validation
    - Rollback plan
    - Stakeholder notification

.PARAMETER Environment
    Target environment: dev, staging, production

.PARAMETER ServiceName
    Service/application name

.PARAMETER Version
    Version being deployed

.PARAMETER OutputFormat
    Output format: markdown (default), html, json

.EXAMPLE
    .\deployment-checklist-generator.ps1 -Environment production -ServiceName "API" -Version "v2.0.0"

.NOTES
    Value: 7/10 - Prevents deployment mistakes
    Effort: 1.2/10 - Template generation
    Ratio: 6.0 (TIER S)
#>

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet('dev', 'staging', 'production')]
    [string]$Environment,

    [Parameter(Mandatory=$true)]
    [string]$ServiceName,

    [Parameter(Mandatory=$true)]
    [string]$Version,

    [Parameter(Mandatory=$false)]
    [ValidateSet('markdown', 'html', 'json')]
    [string]$OutputFormat = 'markdown'
)

# AUTO-USAGE TRACKING
$toolName = $MyInvocation.MyCommand.Name -replace '\.ps1$', ''
. "$PSScriptRoot\_usage-logger.ps1" -ToolName $toolName -Action "execute" -Metadata @{ Parameters = ($PSBoundParameters.Keys -join ',') } -ErrorAction SilentlyContinue

Write-Host "📋 Deployment Checklist Generator" -ForegroundColor Cyan
Write-Host "  Environment: $Environment" -ForegroundColor Gray
Write-Host "  Service: $ServiceName $Version" -ForegroundColor Gray
Write-Host ""

$isProduction = $Environment -eq 'production'

$checklist = @"
# Deployment Checklist: $ServiceName $Version

**Environment:** $Environment
**Date:** $(Get-Date -Format 'yyyy-MM-dd')
**Deployer:** [Your Name]

---

## Pre-Deployment

- [ ] Code review completed and approved
- [ ] All tests passing (unit, integration, e2e)
- [ ] Security scan completed
- [ ] Changelog updated
$( if ($isProduction) { "- [ ] Change advisory created and approved`n- [ ] Stakeholders notified`n- [ ] Maintenance window scheduled" } else { "" })
- [ ] Database migrations tested
- [ ] Configuration verified
- [ ] Rollback plan prepared

## Deployment Steps

1. [ ] **Backup current version**
   - Database backup
   - Configuration backup
   - Binary backup

2. [ ] **Pre-deployment checks**
   - [ ] Verify environment health
   - [ ] Check system resources (CPU, memory, disk)
   - [ ] Verify dependencies available

3. [ ] **Execute deployment**
   - [ ] Stop application/service
   - [ ] Run database migrations
   - [ ] Deploy new version
   - [ ] Update configuration
   - [ ] Start application/service

4. [ ] **Smoke tests**
   - [ ] Application starts successfully
   - [ ] Health check endpoint responding
   - [ ] Database connectivity verified
   - [ ] External integrations working

## Post-Deployment Validation

- [ ] Run automated tests
- [ ] Verify key user flows
- [ ] Check error logs
- [ ] Monitor performance metrics
- [ ] Verify no regressions
$( if ($isProduction) { "- [ ] Update status page`n- [ ] Notify stakeholders of completion" } else { "" })

## Rollback Plan

**If deployment fails:**

1. [ ] Stop application
2. [ ] Restore previous version from backup
3. [ ] Rollback database migrations (if needed)
4. [ ] Restore configuration
5. [ ] Start application
6. [ ] Verify rollback successful
$( if ($isProduction) { "7. [ ] Notify stakeholders of rollback" } else { "" })

## Monitoring

- [ ] Application logs (first 30 minutes)
- [ ] Error rate dashboard
- [ ] Performance metrics
- [ ] User activity patterns
- [ ] System resource usage

## Sign-Off

**Deployed by:** _______________  
**Date/Time:** _______________  
**Deployment Status:** [ ] Success [ ] Rollback  
**Notes:**

---

*Generated by deployment-checklist-generator*
"@

$outputPath = "deployment_checklist_${Environment}_${ServiceName}_${Version}_$(Get-Date -Format 'yyyyMMdd').md"

switch ($OutputFormat) {
    'markdown' {
        $checklist | Set-Content $outputPath -Encoding UTF8
        Write-Host "✅ Checklist generated: $outputPath" -ForegroundColor Green
    }
    'html' {
        $html = @"
<!DOCTYPE html>
<html>
<head>
    <title>Deployment Checklist</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; max-width: 800px; }
        h1 { color: #1976d2; }
        input[type=checkbox] { margin-right: 10px; }
        .section { margin: 30px 0; }
    </style>
</head>
<body>
    $($checklist -replace '\n', '<br>')
</body>
</html>
"@
        $htmlPath = $outputPath -replace '\.md$', '.html'
        $html | Set-Content $htmlPath -Encoding UTF8
        Write-Host "✅ Checklist generated: $htmlPath" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "DEPLOYMENT CHECKLIST READY" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Review checklist items" -ForegroundColor Gray
Write-Host "  2. Execute deployment following checklist" -ForegroundColor Gray
Write-Host "  3. Check off items as completed" -ForegroundColor Gray
Write-Host "  4. Keep checklist for audit trail" -ForegroundColor Gray
