<#
.SYNOPSIS
    Auto-generate summary files for large documentation

.DESCRIPTION
    Creates SUMMARY.md files for documentation that exceeds optimal size.
    Generates executive summaries using AI or structured content extraction.

.PARAMETER FilePath
    Path to file to summarize (if not specified, processes all oversized files)

.PARAMETER OutputSuffix
    Suffix for summary files (default: "_SUMMARY")

.PARAMETER UseAI
    Use AI (Claude API) for intelligent summarization (default: $false)

.PARAMETER MaxSummaryTokens
    Target token count for summaries (default: 2000)

.EXAMPLE
    .\doc-summarizer.ps1 -FilePath "C:\scripts\CLAUDE.md"
    Generate summary for single file

.EXAMPLE
    .\doc-summarizer.ps1 -UseAI $true
    Process all oversized files with AI summarization

.NOTES
    Part of Improvement #4: Smart file size warnings
    Expert: Prof. Emily Bradford (Documentation structure patterns)
#>

param(
    [string]$FilePath = "",
    [string]$OutputSuffix = "_SUMMARY",
    [bool]$UseAI = $false,
    [int]$MaxSummaryTokens = 2000
)

# Extract key sections from markdown content
function Extract-KeySections {
    param([string]$Content)

    $lines = $Content -split "`n"
    $summary = @()
    $inCodeBlock = $false

    foreach ($line in $lines) {
        # Track code blocks
        if ($line -match '^```') {
            $inCodeBlock = -not $inCodeBlock
            continue
        }

        # Skip code blocks
        if ($inCodeBlock) {
            continue
        }

        # Include headers (all levels)
        if ($line -match '^#+\s+(.+)$') {
            $summary += $line
            continue
        }

        # Include key paragraphs (those starting with keywords)
        if ($line -match '^\s*(IMPORTANT|CRITICAL|NOTE|WARNING|MANDATORY|REQUIRED):') {
            $summary += $line
            continue
        }

        # Include bold statements
        if ($line -match '\*\*[^*]+\*\*') {
            $summary += $line
            continue
        }
    }

    return $summary -join "`n"
}

# Generate structured summary
function Generate-StructuredSummary {
    param(
        [string]$FilePath,
        [string]$Content,
        [int]$TargetTokens
    )

    $fileName = [System.IO.Path]::GetFileName($FilePath)
    $keySections = Extract-KeySections -Content $Content

    # Calculate actual size
    $actualTokens = [int]($Content.Length / 4)

    $summary = @"
# Summary: $fileName

**This is an auto-generated summary. For complete details, see: [$fileName](./$fileName)**

---

## Document Overview
- **Full document**: $fileName
- **Approximate size**: $actualTokens tokens
- **Generated**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
- **Summary type**: Structured extraction

---

## Key Sections

$keySections

---

## How to Use This Summary

1. **Quick scan**: Read this summary to understand main topics
2. **Deep dive**: Open full document when you need complete details
3. **Search**: Use Ctrl+F to find specific topics in full document

## Full Document
For complete information, algorithms, examples, and detailed explanations, see:
**→ [$fileName](./$fileName)**

---
*Auto-generated by doc-summarizer.ps1 (Improvement #4)*
*This summary contains approximately $([int]($keySections.Length / 4)) tokens (vs $actualTokens in full document)*
"@

    return $summary
}

# Generate AI-powered summary (placeholder for future implementation)
function Generate-AISummary {
    param(
        [string]$FilePath,
        [string]$Content,
        [int]$TargetTokens
    )

    Write-Host "AI summarization not yet implemented. Using structured extraction." -ForegroundColor Yellow
    return Generate-StructuredSummary -FilePath $FilePath -Content $Content -TargetTokens $TargetTokens
}

# Process single file
function Process-File {
    param(
        [string]$FilePath,
        [bool]$UseAI,
        [int]$TargetTokens
    )

    if (-not (Test-Path $FilePath)) {
        Write-Error "File not found: $FilePath"
        return
    }

    $content = Get-Content -Path $FilePath -Raw
    $tokens = [int]($content.Length / 4)

    Write-Host "Processing: $FilePath" -ForegroundColor Cyan
    Write-Host "  Size: $tokens tokens" -ForegroundColor Gray

    # Generate summary
    if ($UseAI) {
        $summary = Generate-AISummary -FilePath $FilePath -Content $content -TargetTokens $TargetTokens
    }
    else {
        $summary = Generate-StructuredSummary -FilePath $FilePath -Content $content -TargetTokens $TargetTokens
    }

    # Determine output path
    $directory = [System.IO.Path]::GetDirectoryName($FilePath)
    $fileNameWithoutExt = [System.IO.Path]::GetFileNameWithoutExtension($FilePath)
    $outputPath = Join-Path $directory "$fileNameWithoutExt$OutputSuffix.md"

    # Write summary
    Set-Content -Path $outputPath -Value $summary -Encoding UTF8

    $summaryTokens = [int]($summary.Length / 4)
    $reduction = [math]::Round((1 - ($summaryTokens / $tokens)) * 100, 1)

    Write-Host "  Created: $outputPath" -ForegroundColor Green
    Write-Host "  Summary size: $summaryTokens tokens ($reduction% reduction)" -ForegroundColor Green
    Write-Host ""

    return [PSCustomObject]@{
        OriginalFile = $FilePath
        SummaryFile = $outputPath
        OriginalTokens = $tokens
        SummaryTokens = $summaryTokens
        ReductionPercent = $reduction
    }
}

# Main execution
Write-Host "Documentation Summarizer" -ForegroundColor Cyan
Write-Host "Mode: $(if ($UseAI) { 'AI-powered' } else { 'Structured extraction' })" -ForegroundColor Cyan
Write-Host ""

$results = @()

if ($FilePath) {
    # Process single file
    $result = Process-File -FilePath $FilePath -UseAI $UseAI -TargetTokens $MaxSummaryTokens
    if ($result) {
        $results += $result
    }
}
else {
    # Process all oversized files from monitor report
    $reportPath = "C:\scripts\_machine\doc-size-report.md"

    if (Test-Path $reportPath) {
        Write-Host "Reading oversized files from: $reportPath" -ForegroundColor Yellow

        # Parse report to find oversized files
        $reportContent = Get-Content -Path $reportPath -Raw
        $lines = $reportContent -split "`n"

        $filesToProcess = @()
        foreach ($line in $lines) {
            if ($line -match '^\|\s*([^|]+?)\s*\|\s*\d+\s*\|\s*\d+\s*\|\s*(MODERATE|HIGH|CRITICAL)') {
                $relativePath = $matches[1].Trim()
                $fullPath = Join-Path "C:\scripts" $relativePath
                if (Test-Path $fullPath) {
                    $filesToProcess += $fullPath
                }
            }
        }

        if ($filesToProcess.Count -eq 0) {
            Write-Host "No files found in report. Run doc-size-monitor.ps1 first." -ForegroundColor Red
            exit
        }

        Write-Host "Found $($filesToProcess.Count) files to process" -ForegroundColor Yellow
        Write-Host ""

        foreach ($file in $filesToProcess) {
            $result = Process-File -FilePath $file -UseAI $UseAI -TargetTokens $MaxSummaryTokens
            if ($result) {
                $results += $result
            }
        }
    }
    else {
        Write-Host "No report found. Run doc-size-monitor.ps1 first to identify oversized files." -ForegroundColor Red
        Write-Host "Or specify -FilePath to process a specific file." -ForegroundColor Yellow
        exit
    }
}

# Summary
if ($results.Count -gt 0) {
    Write-Host "=" * 80 -ForegroundColor Cyan
    Write-Host "SUMMARY" -ForegroundColor Cyan
    Write-Host "  Files processed: $($results.Count)" -ForegroundColor White
    Write-Host "  Total original tokens: $($results | Measure-Object -Property OriginalTokens -Sum | Select-Object -ExpandProperty Sum)" -ForegroundColor White
    Write-Host "  Total summary tokens: $($results | Measure-Object -Property SummaryTokens -Sum | Select-Object -ExpandProperty Sum)" -ForegroundColor White
    Write-Host "  Average reduction: $([math]::Round(($results | Measure-Object -Property ReductionPercent -Average | Select-Object -ExpandProperty Average), 1))%" -ForegroundColor Green

    Write-Host ""
    Write-Host "NEXT STEPS:" -ForegroundColor Yellow
    Write-Host "  1. Review generated summaries for accuracy" -ForegroundColor White
    Write-Host "  2. Update cross-references to include summary files" -ForegroundColor White
    Write-Host "  3. Add summary files to STARTUP_PROTOCOL.md if critical" -ForegroundColor White
    Write-Host "  4. Re-run doc-size-monitor.ps1 to verify improvements" -ForegroundColor White
    Write-Host "=" * 80 -ForegroundColor Cyan
}
